FIX: Switch to upload artefact v4 (#960)
The CI for uploading package artefacts is failing with the following
error:

```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```

This PR switches the Github action `upload-artifact` to v4.